//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.31 at 02:30:54 ���� CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rtable.dianping.com/shell/config/xsd")
package com.ss.dw.mrshell.config.xsd;
